Algoritmo "Informa a tabuada"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Informa a tabuada de um número
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2020
Var
// variaveis
n,resposta,v:inteiro


Inicio
//entrada
escreval("escreva um número que você deseja saber a tabuada")
leia(n)
para v<- 1 ate 10 faca
resposta<- n*v
escreval(resposta)
fimpara

Fimalgoritmo